### PR TITLE
Enable Bonsai Asset Build

### PR DESCRIPTION
**Pull request by terraboops**
## Pull Request Checklist
Adding Bonzai the same way it was done for this PR:
https://github.com/sensu-plugins/sensu-plugins-network-checks/pull/94

#### General

- [x] Update Changelog following the conventions laid out  [here](https://github.com/sensu-plugins/community/blob/master/HOW_WE_CHANGELOG.md)

- [x] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [x] RuboCop passes

- [x] Existing tests pass

#### Purpose
- Enable Sensu Go Asset building
- Remove unsupported ruby assets

### CODE REVIEW

**Comment by tylermauthe** [comment]
Sorry I don't know if Binstubs are needed...

Let me know if there's anything else you'd like me to change to get this merged. Thanks.

**Comment by tylermauthe** [comment]
Ping!

I think this is a useful PR... I am using a fork of it from here and it's working well:
https://github.com/tylermauthe/sensu-plugins-consul/releases/tag/3.0.0

Anything else I can do to help get this merged @majormoses? 🙇

**Review by majormoses — APPROVED** [review]
LGTM

I would like a second pair of eyes on this one since I am less familiar with bonsai setup.

**Comment by nixwiz** [comment]
@tylermauthe could you take a look at the .bonsai.yaml file in #64 and update this PR to include it?  It has more build targets and it makes use of platform_family to provide better filtering.

**Comment by tylermauthe** [comment]
@nixwiz - when I added that, the build broke
https://travis-ci.org/sensu-plugins/sensu-plugins-consul/builds/642666307

However, I have reverted my changes to the original and it seems the build is still broken. Is master building correctly? Has a new test been added?

Note: I haven't even looked at the error output - but I do notice that all recent builds on PRs are failing.

**Comment by majormoses** [comment]
the failure is the version of bundler being installed in travis differs from what is specified in the gemspec:
- https://travis-ci.org/sensu-plugins/sensu-plugins-consul/jobs/642668468#L241 
- https://github.com/sensu-plugins/sensu-plugins-consul/blob/10f6ecefd7465d7abfdcada17b82505c880dd6e7/sensu-plugins-consul.gemspec#L39

We probably want to specify in the travis file to install/upgrade (a specific version) of bundler before attempting to `bundle` for example: https://github.com/sensu-plugins/sensu-plugins-windows/blob/83a67bf66a33c7b6762c3a7335284501aff1c1bb/.travis.yml#L5.

**Review by nixwiz — COMMENTED** [review]
After updating .travis.yml, also update the bundler dependency in the gemspecl to '~> 2.1' and add these changes to the CHANGELOG.

**Pull request closed without merging**
