### PR TITLE
Use 'Service' key instead of 'ID' key for service discovery

### PR DESCRIPTION
**Pull request by psyhomb**
Hi @majormoses,

I just discovered a bug in my previous PR [#25](https://github.com/sensu-plugins/sensu-plugins-consul/pull/25) that would cause for some services to be skipped during the check process, so I made another PR that's going to fix that.

Basically I was using a value of `ID` key as a service name and these two entities are not always the same, like you can see from this example, second service (svc2) has the same value for `ID` and `Service` key, which is not the case for the first one (svc1), in other words `Service` key is the key that we should rely upon, it will always hold a real service name and that's why we should use it instead of `ID` key for service discovery.

```json
# curl -s http://localhost:8500/v1/agent/services
{
    "svc1-prod": {
        "Address": "",
        "CreateIndex": 0,
        "EnableTagOverride": false,
        "ID": "svc1-prod",
        "ModifyIndex": 0,
        "Port": 8986,
        "Service": "svc1",
        "Tags": [
            "prod"
        ]
    },
    "svc2": {
        "Address": "",
        "CreateIndex": 0,
        "EnableTagOverride": false,
        "ID": "svc2",
        "ModifyIndex": 0,
        "Port": 8988,
        "Service": "svc2",
        "Tags": [
        ]
    }
}  
```

### CODE REVIEW

**Comment by majormoses** [comment]
good, catch, can you add a changelog entry?

**Comment by majormoses** [comment]
Also can I see a gist or something of the input and output?

**Comment by psyhomb** [comment]
Before fix
```
# check-consul-service-health.rb -n node1.example.com

CheckConsulServiceHealth CRITICAL: [{"service:svc2"=>"ERROR: an unknown exception had occurred!\n", "Status"=>"warning"}]
```

After fix
```
# check-consul-service-health.rb -n node1.example.com

CheckConsulServiceHealth CRITICAL: [{"service:svc1"=>"Get http://localhost:8986/healthcheck: dial tcp [::1]:8986: getsockopt: connection refused", "Status"=>"critical"}, {"service:svc2"=>"ERROR: an unknown exception had occurred!\n", "Status"=>"warning"}]
```

**Comment by psyhomb** [comment]
@majormoses is there anything else I can help with regarding this PR?

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-consul/versions/1.4.1

**Pull request merged**
