### PR TITLE
Added 'remove_failed_node' and 'critical' boolean options (check-consul-failures.rb)

### PR DESCRIPTION
**Pull request by psyhomb**
#### General

- [x] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [x] RuboCop passes

- [x] Existing tests pass

#### Improvements

Added support for `--remove-failed-node` and `--critical` arguments in `check-consul-failures.rb`

Show warning if you find failed nodes
```
# check-consul-failures.rb --server consul-server.example.com

ConsulStatus WARNING: Found failed nodes: ["node1.example.com", "node2.example.com"]
```

Show critical if you find failed nodes
```
# check-consul-failures.rb --server consul-server.example.com --critical

ConsulStatus CRITICAL: Found failed nodes: ["node1.example.com", "node2.example.com"]
```

Remove all failing nodes
```
# check-consul-failures.rb --server consul-server.example.com --remove-failed-node

Removing failed node: node1.example.com
Removing failed node: node2.example.com
ConsulStatus OK: All clear
```

OK status
```
# check-consul-failures.rb --server consul-server.example.com

ConsulStatus OK: All nodes are alive
```

### CODE REVIEW

**Comment by psyhomb** [comment]
@majormoses please do ask if you need anything else

**Comment by majormoses** [comment]
@psyhomb I will review this tonight, from what I saw quickly it previously always removed nodes but you want an option to toggle this behavior am I right?

**Comment by psyhomb** [comment]
> you want an option to toggle this behavior am I right
@majormoses, that's correct

> If so this makes it a breaking change
Good point, I can change it to `--keep-failed-node` that way we can keep compatibility with previous version?

**Comment by majormoses** [comment]
Ya if we did not previously have it this way I would have prefered an opt-in experience but I think opt out is the best course of action as it is the difference would be a breaking change and brings little value to the end user for doing so.

I am not opposed to breaking changes by any means but breaking changes should really be guided by maintenance, user experience, etc not just because I personally dislike the logic, naming, etc.

As for naming...I would prefer to keep the tense in present as we are not monitoring the past. I'd vote for something along the lines of:
- `--preserve-failures`
- `--keep-failures`
- `--preserve-node-failures`
- `--keep-node-failures`

**Comment by psyhomb** [comment]
@majormoses the requested changes have been made, and thank you for your detailed review and suggestions.

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-consul/versions/1.5.0

**Pull request merged**
